### ISSUE TITLE
Webpage Update Test State

### ISSUE THREAD

**Issue by LarsPauli** [alxhoff/PAF-controller#4]
After the interrupt has switched off the PWM output the state of the test is not updated on the webpage.

**Comment by alxhoff** [comment]
On it ;)

**Comment by alxhoff** [comment]
Got a little carried away with 0ebf50fee94711adb710c5b9b56cef980460d047 but there should be a solid start for you to go off of. I'm not sure what needs to get set for each test so not sure how to continue.

**Comment by alxhoff** [comment]
Also the code is somewhat unstable. I need to put in proper mutli-thread stuff, will do it tomorrow.

**Comment by alxhoff** [comment]
@LarsPauli
